apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: falco
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Falco + Falcosidekick + Falcosidekick-UI

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "https://github.com/Issif/argo-falco.git"

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: falco
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
